{{- if .Values.admin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lolcatz-admin
spec:
  selector:
    matchLabels:
      app: lolcatz-admin
  template:
    metadata:
      labels:
        app: lolcatz-admin
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: server-tls
          secret:
            secretName: lolcatz-admin-internal-tls
      containers:
        - name: admin
          image: {{ include "lolcatz.image" (dict "registry" .Values.imageRegistry "image" .Values.admin.image) }}
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 9090
            - name: https
              containerPort: 8080
          securityContext:
            readOnlyRootFilesystem: true
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
          resources:
            {{- toYaml .Values.admin.resources | nindent 12 }}
          volumeMounts:
            - name: server-tls
              mountPath: /etc/server-tls
              readOnly: true
          env:
            - name: TLS_CERT_FILE
              value: /etc/server-tls/tls.crt
            - name: TLS_KEY_FILE
              value: /etc/server-tls/tls.key
            - name: REDIS_TLS
              value: "true"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lolcatz-redis-password
                  key: password
            - name: PGSSLMODE
              value: verify-full
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lolcatz-database-app
                  key: uri
            - name: REDIS_ADDR
              value: lolcatz-redis.{{ .Release.Namespace }}.svc.cluster.local:6379
            - name: OIDC_CLIENT_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: oidc-client-lolcatz-frontend-owner-secrets
                  key: OIDC_CLIENT_ORIGIN
            - name: OIDC_AUDIENCE
              value: "$(OIDC_CLIENT_ORIGIN)/api"
            - name: OIDC_ISSUER
              valueFrom:
                secretKeyRef:
                  name: oidc-client-lolcatz-frontend-owner-secrets
                  key: OIDC_IDP_URI
{{- end }}
