apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: lolcatz-redis
spec:
  authentication:
    passwordFromSecret:
      name: lolcatz-redis-password
      key: password
  resources:
    {{- toYaml .Values.redis.resources | nindent 4 }}
