{{- if .Values.internalTLS.enabled }}
{{- range $name := list "admin" "browse" "comments" "frontend" "search" "thumbnailer" "uploader" }}
{{- if or (ne $name "admin") $.Values.admin.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: lolcatz-{{ $name }}
spec:
  serverName: lolcatz-{{ $name }}.{{ $.Release.Namespace }}.svc.cluster.local
{{- end }}
{{- end }}
{{- end }}
