apiVersion: s3.onyxia.sh/v1alpha1
kind: S3User
metadata:
  name: lolcatz-storage
spec:
  s3InstanceRef: minio/default
  accessKey: {{ .Release.Namespace }}.lolcatz-storage
  policies:
    - {{ .Release.Namespace }}.to.{{ .Release.Namespace }}.lolcatz-storage
