{{- if not .Values.storage.existingPolicy }}
apiVersion: s3.onyxia.sh/v1alpha1
kind: Policy
metadata:
  name: lolcatz-storage
  annotations:
    s3.codemowers.io/bucket: lolcatz
    s3.codemowers.io/recipient: {{ .Release.Namespace | quote }}
    s3.codemowers.io/access: write
spec:
  s3InstanceRef: minio/default
  name: {{ .Release.Namespace }}.to.{{ .Release.Namespace }}.lolcatz-storage
  policyContent: |
    {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:ListBucket","s3:GetBucketLocation"],"Resource":["arn:aws:s3:::{{ .Release.Namespace }}.lolcatz"]},{"Effect":"Allow","Action":["s3:GetObject","s3:PutObject","s3:DeleteObject","s3:AbortMultipartUpload","s3:ListMultipartUploadParts"],"Resource":["arn:aws:s3:::{{ .Release.Namespace }}.lolcatz/*"]}]}
{{- end }}
