apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lolcatz-database
  labels:
    skaffold.dev/keep: "true"
  annotations:
    helm.sh/resource-policy: keep
spec:
  postgresql:
    extensions:
      - name: pgvector
        image:
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.1-18-trixie
      - name: postgis
        ld_library_path:
          - system
        image:
          reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.2-18-trixie
  bootstrap:
    initdb:
      database: lolcatz
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: lolcatz
  storage:
    size: {{ .Values.database.storage }}
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m
