apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: lolcatz-redpanda
  labels:
    skaffold.dev/keep: "true"
spec:
  chartRef: {}
  clusterSpec:
    tls:
      certs:
        default:
          caEnabled: true
          secretRef:
            name: lolcatz-redpanda-internal-tls
    auth:
      sasl:
        enabled: true
        secretRef: lolcatz-redpanda-users
    resources:
      {{- toYaml .Values.redpanda.resources | nindent 6 }}
    storage:
      persistentVolume:
        size: {{ .Values.redpanda.storage }}
